### ISSUE TITLE
renovar domínio porque expira 12/12/2015

### ISSUE THREAD

**Issue by luzfcb** [dojoto/dojoto.github.io#12]
Problema: To sem grana....

![captura de tela de 2015-09-15 08 49 40](https://cloud.githubusercontent.com/assets/807599/9875703/c2fc7f20-5b86-11e5-84f0-403dd10cbac2.png)

**Comment by luzfcb** [comment]
@dojoto/owners aff ta caro para renovar...
![aaa](https://cloud.githubusercontent.com/assets/807599/10366597/d78faf84-6da1-11e5-924b-af32b1e729d9.png)

**Comment by v4ires** [comment]
Nossa mano ta super caro!

**Comment by v4ires** [comment]
O que você acha de comprarmos um domínio no registro.br?
*da uma olhada tem disponível o dojoto.com.br
https://registro.br/cgi-bin/nicbr/documento?fqdn=dojoto.com.br

**Comment by luzfcb** [comment]
ultimo dia

**Comment by v4ires** [comment]
Eu tenho o dinheiro em espécie mas eu estou sem cartão de crédito, seria possível tu pagar e eu te passar o dinheiro dps?

**Comment by luzfcb** [comment]
Paguei a renovação por 1 ano. R$ 52,72

**Comment by v4ires** [comment]
Opa vlw Fábio :+1: , eu estou vendo para fazer um Coding Dojo de C++ e STL para sexta-feira da semana que vem!

**Comment by luzfcb** [comment]
:+1:

**Comment by v4ires** [comment]
Tá bem corrido essas reposições de aula pós greve na UFT mas vamos fazer ao menos mais um antes de terminar o ano!
