### ISSUE TITLE
Problema com Link dojoto.xyz

### ISSUE THREAD

**Issue by v4ires** [dojoto/dojoto.github.io#17]
Percebi que mesmo depois das mudanças feitas sobre o novo domínio do site DojoTO alguns Links estão indo para produção quebrados, apontando para o antigo domínio.

**Comment by luzfcb** [comment]
@viniciusaires tem que regerar as chaves ssh de commit, e publica-las no travis... eu ainda não tive tempo para fazer isso

**Comment by v4ires** [comment]
Tranquilo, sem pressa @luzfcb foi apenas para formalizar o problema aqui no repositório :+1:

**Comment by v4ires** [comment]
Fala como faz isso que eu quando puder a noite faço a atualização dessas chaves @luzfcb :smile:

**Comment by luzfcb** [comment]
problema corrigido...
